version: "3"

services:
  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: libretranslate
    restart: always
    ports:
      - "5000:5000"
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
    #environment:
      # LT_LOAD_ONLY: en,de # en,es,de
    volumes:
      #- /opt/libretranslate_models:/home/libretranslate/.local:rw
      - ./data:/home/libretranslate/.local:rw
    deploy:
      resources:
        limits:
          cpus: '0.85'
          memory: 6G
